INSERT INTO TODO(ID,USERNAME,DESCRIPTION,DONE,TARGET_DATE)
VALUES(2, 'Admin','learn some',FALSE,'2022-06-10');

INSERT INTO TODO(ID,USERNAME,DESCRIPTION,DONE,TARGET_DATE)
VALUES(1, 'Admin','learn aws',TRUE,'2023-01-10');

INSERT INTO TODO(ID,USERNAME,DESCRIPTION,DONE,TARGET_DATE)
VALUES(3, 'Dev','deploy app',FALSE,'2023-01-10');